# Generated by Django 4.0.5 on 2022-06-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='category',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='media',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='media',
            name='id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='media',
            name='thumb',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='media',
            name='video',
            field=models.CharField(max_length=1000),
        ),
    ]
